apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "http-pulsar-router.fullname" . }}
  labels:
    {{- include "http-pulsar-router.labels" . | nindent 4 }}
data:
  config.json: |
{{ include "http-pulsar-router.effectiveConfig" . | indent 4 }}
